services:
- type: web
  name: ghost
  env: docker
  autoDeploy: false
  disk:
    name: ghost
    mountPath: /var/lib/ghost/content
    sizeGB: 10
  envVars:
    - key: database__client
      value: mysql # Can be replaced with 'sqlite'
    - key: database__connection__host
      fromService:
        name: ghost-mysql
        type: pserv
        property: host
    - key: database__connection__port
      value: 3306
    - key: database__connection__database
      fromService:
        name: ghost-mysql
        type: pserv
        property: MYSQL_DATABASE
    - key: database__connection__user
      fromService:
        name: ghost-mysql
        type: pserv
        property: MYSQL_USER
    - key: database__connection__password
      fromService:
        name: ghost-mysql
        type: pserv
        property: MYSQL_PASSWORD

- type: pserv
  name: ghost-mysql
  repo: https://github.com/render-examples/mysql
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: ghost-group

envVarGroups:
- name: ghost-group
  envVars:
  - key: MYSQL_DATABASE
    value: ghost
  - key: MYSQL_USER
    value: ghost-db-user
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
